name: Swift Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-14 # Usa um computador Mac virtual

    steps:
    - uses: actions/checkout@v4 # Baixa seu código
    
    - name: Run Tests
      run: |
        xcodebuild test -scheme YearDotsCountdown -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
